export const text =
  "Descubre la sabiduría divina en cada parábola y permite que la esperanza guíe tu camino hacia la plenitud espiritual.";
export const subText =
  "Conoce nuestra organización. Descubre lo que hacemos y cómo queremos hacer del mundo un lugar mejor.";
export const historia =
  "La voluntad de Dios es perfecta y sabemos que los planes del Creador están siempre por encima de cualquier idea o intención humana, su voluntad Divina obra siempre en nuestro beneficio, por tanto, es imprescindible escuchar la voz de Dios y escuchando, saber su voluntad y su agrado. Hemos sido creados a su imagen y semejanza, con talentos y dones para que sean aplicados con sabiduría en el cuerpo de Cristo como guía en nuestras acciones durante nuestra vida. El conocimiento acerca de las metodologías de organización y administración no son nuevas en el mundo, la Palabra de Dios habla desde Moisés, cómo estos conocimientos de la administración ayudaron al gobierno del pueblo hebreo y más todavía, con la venida de nuestro señor Jesucristo, como ejecutor del Plan de Salvación, nos lleva a “escuchar la voz de Dios”, mediante un ejercicio de planificación estratégica. Hemos emprendido el camino para cumplir con un cometido que nuestro salvador nos ha entregado, en donde somos instrumentos de su gracia, esa responsabilidad hace que atendamos a su voz para conocer la ruta que habremos de seguir, con una metodología que su Divina Gracia nos ha permitido conocer, con los dones y talentos que nos ha concedido y con la intención de cumplir con su voluntad santa y perfecta. Se incentivó a realizar un trabajo participativo, para que todos los miembros fundadores de la Corporación Red Cristiana Militar, estén conscientes del camino que emprenderemos, la participación e integración de cada miembro de la Corporación Recmil, se ha hecho en presencia de Dios, en comunión con Él, en oración, porque de lo contrario no podríamos escuchar su voz. Se ha definido la misión que deberemos cumplir con todo entusiasmo, una visión de futuro, que con el “ñeque” característico de un militar podremos lograrlo, basados en principios fundamentales que cimentan nuestra corporación y valores que cada miembro abanderará en su vida diaria. Todo lo anteriormente expuesto se ha realizado iniciando con el análisis y diagnóstico institucional, considerando las fortalezas, debilidades, oportunidades y amenazas encontradas en el ámbito externo las primeras y en el externo las últimas. Del análisis realizado se ha logrado diseñar estrategias, que más adelante, siendo debidamente organizadas, conformarán el direccionamiento estratégico, que será el camino para llegar a la visión trazada. Es momento de unir a quienes forman parte de la corporación, para que juntos y unánimes elevemos nuestra oración a Dios, para pedirle nos conceda la fe, la esperanza y  el amor para cumplir el cometido que se nos ha encomendado; que su provisión sea oportuna y que su gracia nunca nos abandone, confiados todos que estaremos siempre en su presencia y bajo su protección.";
export const mision =
  "Somos seguidores de Jesucristo que servimos a la familia militar en su desarrollo espiritual y personal, mediante actividades de voluntariado, apoyo social y motivacional, para mejorar su calidad de vida con valores y principios auténticos.";
export const vision =
  "La corporación Red Cristiana Militar en el 2027 es reconocida como una organización de apoyo importante para la Fuerza Pública ecuatoriana en el desarrollo de su personal y sus familias, cubre todos los ambientes geográficos en donde se desarrollen sus actividades profesionales, utiliza tecnología avanzada con talento humano certificado y capacitado en técnicas y métodos de educación y formación cristianas.";
